### ISSUE TITLE
window环境下rule无法正常加载

### ISSUE THREAD

**Issue by louisV7** [MiYogurt/egg-y-validator#2]
我的开发环境是win10
app/extend/context.js:57:7
`delStr(app.config.baseDir + '/app/schemas/')`
在windows下app.config.baseDir 中是用的'\'不是'/'，导致拼接后的字符串在delStr时没有删除baseDir部分，最终在执行
`rules = R.path(path, this.docs);`
时为undefine
我自己加了句
`const baseDir = app.config.baseDir.replace(/\\/g, '/');`
替换一下就可以了。。。

**Comment by MiYogurt** [comment]
已修复，使用 v1.1.5 版本即可。

**Comment by louisV7** [comment]
emmm 
还差一点...
`glob.sync(matchPath + '/**/*')`
得到的总是'/'

**Comment by MiYogurt** [comment]
你在测试下 v1.1.7 版本
